---
# See https://github.com/actions/virtual-environments

name: Test Code on OS/X
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
permissions:
    contents: read
jobs:
  build:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        perl: ['5.38', '5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v5
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install packages
        run: |
          brew upgrade
          brew update
          brew outdated
          brew install berkeley-db
          brew cleanup
      - name: Install Dependencies
        run: |
          cpanm -iqn ExtUtils::MakeMaker Test::Most
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Make Module
        env:
          AUTOMATED_TESTING: 1
          NO_NETWORK_TESTING: 1
          NONINTERACTIVE_TESTING: 1
        run: |
          # find . -name build.log | xargs cat
          perl Makefile.PL
          make
      - name: Run Tests
        env:
          AUTOMATED_TESTING: 1
          NO_NETWORK_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          # CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: prove -l -b t
        # run: |
        #   cover -test
        #   cover -report codecov
        #   curl -Os https://uploader.codecov.io/latest/macos/codecov
        #   chmod +x codecov
        #   ./codecov -t ${{ secrets.CODECOV_TOKEN }}
